### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by pgassmann** [markuman/hetzner_dns#3]
if the zone in `zone_name` does not exist, then the check mode looks ok, but when applying without check, the following error appears, which is not helpful to see whats wrong.

The same error message also is shown when the type is wrong. e.g. `type: CNAMES`

And the same error happens also when trying to replace a CNAME record with an A record

perhaps you can fail with a more speaking error message if the zone is not found. https://vincent.bernat.ch/en/blog/2020-custom-ansible-module#error-handling

```
TASK [add record testing123] ***************************************************************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors.AnsibleError: Unknown Error
fatal: [localhost]: FAILED! => changed=false 
  module_stderr: |-
    Traceback (most recent call last):
      File "<stdin>", line 102, in <module>
      File "<stdin>", line 94, in _ansiballz_main
      File "<stdin>", line 40, in invoke_module
      File "/usr/lib/python3.8/runpy.py", line 207, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_markuman.hetzner_dns.record_payload_h4wipiam/ansible_markuman.hetzner_dns.record_payload.zip/ansible_collections/markuman/hetzner_dns/plugins/modules/record.py", line 148, in <module>
      File "/tmp/ansible_markuman.hetzner_dns.record_payload_h4wipiam/ansible_markuman.hetzner_dns.record_payload.zip/ansible_collections/markuman/hetzner_dns/plugins/modules/record.py", line 129, in main
      File "/tmp/ansible_markuman.hetzner_dns.record_payload_h4wipiam/ansible_markuman.hetzner_dns.record_payload.zip/ansible_collections/markuman/hetzner_dns/plugins/module_utils/helper.py", line 94, in update_record
    ansible.errors.AnsibleError: Unknown Error
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1

```

**Comment by markuman** [comment]
> if the zone in zone_name does not exist, then the check mode looks ok, but when applying without check, the following error appears, which is not helpful to see whats wrong.


```yml
        - name: add record
          markuman.hetzner_dns.record:
            zone_name: none_existing
            name: hetzner_dns_ansible_collection
            value: osuv.de.
            type: CNAME
            ttl: 300
          register: RECORD
```

OK, got it.  
The error handling is a bit lazy atm.  
But I can return the API response code with its meaning

```
200 - Successful response
401 - Unauthorized
403 - Forbidden
404 - Not found
406 - Not acceptable
409 - Conflict
422- Unprocessable entity 
```

> The same error message also is shown when the type is wrong. e.g. type: CNAMES

When the `type` is wrong, the error message looks clear for me:

```yml
        - name: add record with wrong type
          markuman.hetzner_dns.record:
            zone_name: osuv.de
            name: hetzner_dns_ansible_collection
            value: osuv.de.
            type: CNAMES
            ttl: 300
          register: RECORD
```

results in 

```
TASK [add record] ****************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "value of type must be one of: A, AAAA, NS, MX, CNAME, RP, TXT, SOA, HINFO, SRV, DANE, TLSA, DS, CAA, got: CNAMES"}
```

This is handled automagically by `AnsibleModule()` when using `choices`: https://github.com/markuman/hetzner_dns/blob/main/plugins/modules/record.py#L61


> And the same error happens also when trying to replace a CNAME record with an A record

Ok, I can reproduce.  
Theoretically the fix is easy. Just remove one line, so it just compares the requested `name`.  
But the API update request response with `http 422`. 

> type required string (RecordTypeCreatable) 

I guess the type is not changeable once it is created. The only way to resolve a type-change is to delete the record and recreate it with different type and value. Thats the same process when changing a type directly with bind9.

**Comment by markuman** [comment]
```yml
        - name: add record
          markuman.hetzner_dns.record:
            zone_name: none_existing
            name: hetzner_dns_ansible_collection1
            value: osuv.de.
            type: CNAME
            ttl: 60
          register: RECORD
          ignore_errors: yes

        - debug: msg="{{ RECORD }}"
```

results with `1.3.0` in 

```
TASK [add record] ****************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "zone or zone_id: Not found."}
...ignoring

TASK [debug] *********************************************************************************************************************
ok: [localhost] => {
    "msg": {
        "changed": false,
        "failed": true,
        "msg": "zone or zone_id: Not found."
    }
}

PLAY RECAP ***********************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=1   
```

**Comment by markuman** [comment]
Other http response code are covered also - in case the API is returning them.  
Under certain circumstances, the API can response 200, even when the resource is not found. To the `404` covers just API endpoints that does not exists I guess.  
Mostly the API will return `422- Unprocessable entity ` in error case.
